[tool.poetry]
name = "harmony"
version = "0.1.0"
description = ""
authors = ["Tommaso Bianco <tommaso.bianco@gmail.com>"]
readme = "README.md"
packages = [{include = "harmony", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
