@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

HIDE_STEREOTYPE()

title System context diagram

Person(user, "User")

ContainerDb(candidate, "Candidate information", "Candidate information", "Holds searchable documents")

Boundary(positions, "Positions") {
    ContainerDb(positions_db, "A database of positions", "", "")
    Container(positions_serv, "A service that manages positions", "", "")
}

Rel(user, positions, "Uses", "https")

SHOW_FLOATING_LEGEND()
Lay_Distance(LEGEND(), athena, 1)

@enduml